In [39]:
import numpy as np
import pandas as pd

In [ ]:
# 29 septiembre 2026
pd.__version__

'2.3.3'

In [29]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')
df.head()


,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   model_year           10000 non-null  int64  
 1   origin               10000 non-null  object 
 2   fuel_type            10000 non-null  object 
 3   drivetrain           10000 non-null  object 
 4   num_doors            10000 non-null  int64  
 5   engine_displacement  10000 non-null  int64  
 6   num_cylinders        10000 non-null  int64  
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64  
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), object(3)
memory usage: 859.5+ KB


In [31]:
df['fuel_type'].unique()

array(['Gasoline', 'Diesel', 'Hybrid'], dtype=object)

In [32]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [33]:
df_Asia = df[df['origin'] == 'Asia']
resultado = df_Asia['fuel_efficiency_mpg'].max()
resultado

np.float64(41.2)

In [34]:
# Q6 Median value of horsepower and the most frequent value of horsepower
median = df['horsepower'].median()
most_frequent = df['horsepower'].mode()[0]
print(f"Median: {median}, Most Frequent: {most_frequent}")

Median: 254.0, Most Frequent: 252.0


In [35]:
"""
Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
Now, calculate the median value of horsepower once again.
Has it changed?

R: yes, it decreased
"""

df['horsepower'] = df['horsepower'].fillna(most_frequent)
df['horsepower'].median()

np.float64(252.0)

In [36]:
# que columnas ve pandas?
print(df.columns)
# indice tiene nombre?
print(df.index.name)


Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='object')
None


In [44]:
# Q7. Sum of weights
"""
Select all the cars from Asia
Select only columns vehicle_weight and model_year
Select the first 7 values
Get the underlying NumPy array. Let's call it X.
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Invert XTX.
Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
What's the sum of all the elements of the result?

"""

df_Asia_cols = df_Asia[['vehicle_weight', 'model_year']]

#convertir a numpy array
X = df_Asia_cols[:7].to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [45]:
# calculando multiplicacion; Transpuesta de X por X
XTX = np.dot(X.T, X)
XTX


array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [46]:
# invertir XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [ ]:
# Creando array y
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

# Multiplicando inversa de XTX por transpuesta de X y luego por y
# Ecuacion normal de la regresion lineal: w = (X^T * X)^-1 * X^T * y
w = np.dot(XTX_inv, np.dot(X.T, y))

print(w)
print(w.sum())

[0.13644777 0.2327492 ]
0.3691969690492593
